### ISSUE TITLE
TCP NS-Bit

### ISSUE THREAD

**Issue by josemic** [msantos/pkt#20]
http://en.wikipedia.org/wiki/Transmission_Control_Protocol (chapter: TCP segment structure, Picture)

defines a NS (ECN-nonce concealment protection) bit.
This bit is not decoded by pkt_tcp:codec(..).
According to Wikipedia the bit is defined in RFC 3540.

**Comment by ates** [comment]
Done in https://github.com/msantos/pkt/commit/a85b50b9eccaa355f8222e8cd35f6319bf4d2c2d
