### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sargun** [msantos/pkt#31]
@msantos What's the license of this repo?

**Comment by msantos** [comment]
On Wed, Apr 13, 2016 at 12:55:58PM -0700, Sargun Dhillon wrote:
> @msantos What's the license of this repo?

It's a BSD license (the license is in the header of each file).

**Comment by msantos** [comment]
@sargun If the license doesn't work for you, we can figure something out. I'm slowly moving to the ISC license.

If you have any other questions or suggestions, please let me know!

**Comment by sargun** [comment]
Thanks. Closed.
