### ISSUE TITLE
bag in pack/unpack router solic

### ISSUE THREAD

**Issue by alexshavelev** [msantos/pkt#44]
https://github.com/msantos/pkt/blob/master/src/pkt_icmp6.erl#L103    - Res = 4 bytes
https://github.com/msantos/pkt/blob/master/src/pkt_icmp6.erl#L112    - Res packs in 2 bytes

**Comment by msantos** [comment]
Good catch, thanks @alexshavelev ! I'll see if I can get a packet dump of a router solicitation to add to the tests.

**Comment by alexshavelev** [comment]
think i can give packet example tomorrow
